name: Curriculum CI

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['node:14-alpine', 'node:15-alpine']
    container: ${{ matrix.node_version }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Eslint
        run: yarn run lint
      - name: Stylelint
        run: yarn run lint:css

  release:
    name: "Release"
    needs: [lint]
    if: ${{ github.repository == 'Its-Alex/curriculum' && contains(github.ref, 'refs/heads/master') }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SPACEFILL_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.SPACEFILL_DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: itsalex/curriculum:stable
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}